# tomcat
server:
  port: 8002

# eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://192.168.0.146:1001/eureka/

# feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 5000

# hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

# tx-lcn
tm:
  manager:
    url: http://192.168.0.146:7000/tx/manager/

# spring
spring:
  application:
    name: service-order

  # database
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

  # redis
  redis:
    database: 0
    host: 192.168.0.146
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1

  data:
    # mongodb
    mongodb:
      uri: mongodb://192.168.0.146:27017/shop

    # elasticsearch
    elasticsearch:
      cluster-name: d2cmall-es
      cluster-nodes: 192.168.0.146:9300

  # rabbitmq
  rabbitmq:
    host: 192.168.0.146
    port: 5672
    username: guest
    password: guest


######################################################### cluster ######################################################

#  # redis
#  redis:
#    database: 0
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    cluster:
#      nodes:
#        - 192.168.0.143:7001
#        - 192.168.0.143:7002
#        - 192.168.0.143:7003
#        - 192.168.0.143:7004
#        - 192.168.0.143:7005
#        - 192.168.0.143:7006

#  data:
#  # mongodb
#    mongodb:
#      uri: mongodb://192.168.0.143:27017,192.168.0.144:27017,192.168.0.145:27017/shop

#  # elasticsearch
#    elasticsearch:
#      cluster-name: d2cmall-es
#      cluster-nodes: 192.168.0.143:9300,192.168.0.144:9300,192.168.0.145:9300

